from pathlib import Path
path = Path('src/app/admin/password/page.tsx')
lines = path.read_text('utf-8').splitlines()
start = 412
end = 585
replacement = [
    '      {managingAlbum && (',
    '        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/55 px-4 py-4 backdrop-blur-sm">',
    '          <div className="relative w-full max-w-6xl max-h-[calc(100vh-4rem)] flex flex-col overflow-hidden rounded-3xl border border-[#f3e1cc] bg-white/95 p-5 shadow-[0_20px_70px_rgba(120,58,12,0.24)] backdrop-blur-xl md:p-6">',
    '            <button',
    '              type="button"',
    '              onClick={() => {',
    '                setManagingAlbum(null);',
    '                setPhotos([]);',
    '                setPhotoNextPageToken(null);',
    '                setHasMorePhotos(false);',
    '                setTotalPhotoCount(0);',
    '              }}',
    '              className="absolute right-4 top-4 inline-flex h-9 w-9 items-center justify-center rounded-full border border-[#e3d2bf] bg-[#fff4e8] text-[#5b3f2c] transition hover:bg-[#ffe6cf]"',
    '              aria-label={isTh ? "ปิด" : "Close"}',
    '            >',
    '              <X className="h-4 w-4" />',
    '            </button>',
    '',
    '            <div className="flex-1 min-h-0 flex flex-col overflow-hidden">',
    '              <div className="mb-5 pr-12">',
    '                <h3 className="text-xl font-bold text-[#2b1a10] md:text-2xl">',
    '                  {isTh ? "จัดการรูปในอัลบัม" : "Manage Album Photos"}: {managingAlbum.name}',
    '                </h3>',
    '                <p className="mt-1 text-sm text-[#6f5a4b]">',
    '                  {isTh',
    '                    ? `กำลังแสดง ${photos.length}/${totalPhotoCount || photos.length} รูป | พบ ${filteredPhotos.length} รูป`',
    '                    : `Showing ${photos.length}/${totalPhotoCount || photos.length} photos | ${filteredPhotos.length} matched`}',
    '                </p>',
    '              </div>',
    '',
    '              <div className="mb-4 rounded-2xl border border-[#ead7c2] bg-[#fff7ee] p-3">',
    '                <p className="mb-2 text-xs font-semibold tracking-[0.08em] text-[#8a6347] uppercase">',
    '                  {isTh ? "เปลี่ยนชื่ออัลบัม" : "Rename album"}',
    '                </p>',
    '                <div className="flex gap-2">',
    '                  <input',
    '                    type="text"',
    '                    value={renameAlbumName}',
    '                    onChange={(e) => setRenameAlbumName(e.target.value)}',
    '                    placeholder={isTh ? "ชื่ออัลบัมใหม่" : "New album name"}',
    '                    className="h-10 w-full rounded-xl border border-[#e3d2bf] bg-white px-3 text-sm text-[#3f2b1d] outline-none focus:border-[#ff7a2e] focus:ring-2 focus:ring-[#ff7a2e]/20"',
    '                  />',
    '                  <button',
    '                    type="button"',
    '                    onClick={handleRenameAlbum}',
    '                    disabled={renamingAlbum || !renameAlbumName.trim()}',
    '                    className="h-10 shrink-0 rounded-xl bg-primary px-4 text-sm font-semibold text-white disabled:opacity-60"',
    '                  >',
    '                    {renamingAlbum',
    '                      ? isTh',
    '                        ? "กำลังบันทึก..."',
    '                        : "Saving..."',
    '                      : isTh',
    '                        ? "บันทึก"',
    '                        : "Save"}',
    '                  </button>',
    '                </div>',
    '              </div>',
    '',
    '              <div className="mb-4 rounded-2xl border border-[#ead7c2] bg-[#fff7ee] p-3">',
    '                <label className="mb-2 block text-xs font-semibold tracking-[0.08em] text-[#8a6347] uppercase">',
    '                  {isTh ? "ค้นหารูปเพื่อลบ" : "Search photos to delete"}',
    '                </label>',
    '                <div className="relative">',
    '                  <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#a27e63]" />',
    '                  <input',
    '                    type="text"',
    '                    value={photoSearch}',
    '                    onChange={(e) => setPhotoSearch(e.target.value)}',
    '                    placeholder={isTh ? "พิมพ์ชื่อไฟล์" : "Type filename"}',
    '                    className="h-10 w-full rounded-xl border border-[#e3d2bf] bg-white px-10 text-sm text-[#3f2b1d] outline-none focus:border-[#ff7a2e] focus:ring-2 focus:ring-[#ff7a2e]/20"',
    '                  />',
    '                </div>',
    '              </div>',
    '',
    '              {photosLoading ? (',
    '                <div className="flex-1 min-h-0 flex items-center justify-center text-center text-sm text-[#6f5a4b]">',
    '                  {isTh ? "กำลังโหลดรูปภาพ..." : "Loading photos..."}',
    '                </div>',
    '              ) : filteredPhotos.length === 0 ? (',
    '                <div className="flex-1 min-h-0 flex items-center justify-center text-center text-sm text-[#6f5a4b]">',
    '                  {photoSearch',
    '                    ? isTh',
    '                      ? "ไม่พบรูปที่ตรงกับคำค้นหา"',
    '                      : "No photos match"',
    '                    : isTh',
    '                      ? "ยังไม่มีรูปในอัลบัมนี้"',
    '                      : "No photos in this album"}',
    '                </div>',
    '              ) : (',
    '                <div',
    '                  className="flex-1 min-h-0 overflow-y-auto pr-1"',
    '                  onScroll={handlePhotosScroll}',
    '                >',
    '                  <div className="grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-4">',
    '                    {filteredPhotos.map((photo) => (',
    '                      <div',
    '                        key={photo.id}',
    '                        className="overflow-hidden rounded-xl border border-[#efddca] bg-[#fff7ee]"',
    '                      >',
    '                        <Image',
    '                          src={',
    '                            failedPhotoIds.includes(photo.id)',
    '                              ? "/logo.png"',
    '                              : photo.previewUrl ||',
    '                                photo.downloadUrl ||',
    '                                "/logo.png"',
    '                          }',
    '                          alt={photo.name}',
    '                          width={320}',
    '                          height={320}',
    '                          className="aspect-square w-full object-cover"',
    '                          unoptimized',
    '                          onError={(e) => {',
    '                            const target = e.currentTarget as HTMLImageElement;',
    '                            if (target.src.includes("/logo.png")) return;',
    '                            setFailedPhotoIds((prev) =>',
    '                              prev.includes(photo.id)',
    '                                ? prev',
    '                                : [...prev, photo.id]',
    '                            );',
    '                          }}',
    '                        />',
    '                        <div className="space-y-2 p-3">',
    '                          <p',
    '                            className="truncate text-xs text-[#6a5445]"',
    '                            title={photo.name}',
    '                          >',
    '                            {photo.name}',
    '                          </p>',
    '                          <button',
    '                            type="button"',
    '                            onClick={() =>',
    '                              setConfirmState({',
    '                                type: "delete-photo",',
    '                                album: managingAlbum,',
    '                                photo,',
    '                              })',
    '                            }',
    '                            disabled={deletingPhotoId === photo.id}',
    '                            className="inline-flex w-full items-center justify-center gap-1.5 rounded-lg border border-red-200 bg-red-50 px-2 py-1.5 text-xs font-medium text-red-700 transition hover:bg-red-100 disabled:opacity-60"',
    '                          >',
    '                            <Trash2 className="h-3.5 w-3.5" />',
    '                            {deletingPhotoId === photo.id',
    '                              ? isTh',
    '                                ? "กำลังลบ..."',
    '                                : "Deleting..."',
    '                              : isTh',
    '                                ? "ลบรูปนี้"',
    '                                : "Delete Photo"}',
    '                          </button>',
    '                        </div>',
    '                      </div>',
    '                    ))}',
    '                  </div>',
    '',
    '                  {photosLoadingMore && (',
    '                    <div className="mt-4 text-center text-sm text-[#6f5a4b]">',
    '                      {isTh ? "กำลังโหลดรูปเพิ่ม..." : "Loading more photos..."}',
    '                    </div>',
    '                  )}',
    '',
    '                  {!photosLoadingMore && hasMorePhotos && (',
    '                    <div className="mt-4 text-center text-sm text-[#8a6347]">',
    '                      {isTh ? "เลื่อนลงเพื่อดูภาพเพิ่มเติม" : "Scroll down to load more photos"}',
    '                    </div>',
    '                  )}',
    '                </div>',
    '              )}',
    '            </div>',
    '          </div>',
    '        </div>',
    '      )}',
    '',
    '      {confirmState && (',
]

new_lines = lines[:start] + replacement + lines[end:]
path.write_text('\n'.join(new_lines) + '\n', 'utf-8')
print('done')
